### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by edanurakss** [Nello796/Simple-Data-Entry#1]
Hello,

When I open or try to do something in the index, this message shows up:

Sorry, there was a problem with the server.

Error: error (0)

Could you help me?

**Comment by Nello796** [comment]
Hi,

Yes, absolutely! Have you checked the console?

**Comment by edanurakss** [comment]
Yes i checked but it seems it don't see contacts.txt. When I click on form error message on the screen and no contact data from txt.
Is that permission related?

**Comment by Nello796** [comment]
Can you write here what the console prints when you try to add a new entry please? it may be a permission issue related

**Comment by edanurakss** [comment]
This is the message
"Sorry, there was a problem with the server.

Error: error (0)"

**Comment by Nello796** [comment]
Are you using apache to run web server?

**Comment by Nello796** [comment]
Are you using apache to run it?
